min-players: 2
countdown: 10
lobby:
  world: 'world'
  x: -408.0
  y: 64.0
  z: -170.0
  pitch: 0.0
  yaw: 0.0
arenas:
  0:
    world: 'world'
    name: 'Allah Kerim'
    x: -408.0
    y: 64.0
    z: -170.0
    pitch: 0.0
    yaw: 0.0
  1:
    world: 'world'
    name: 'Allah Kerim2'
    x: -408.0
    y: 64.0
    z: -170.0
    pitch: 0.0
    yaw: 0.0